# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM golang:1.24-alpine AS builder

WORKDIR /src

# Install git for go mod download
RUN apk add --no-cache git

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the binary with the new Go version
RUN CGO_ENABLED=0 go build -o /app/dingtalk-mcp main.go

FROM alpine:latest

# Copy the binary from builder
COPY --from=builder /app/dingtalk-mcp /app/dingtalk-mcp

# Set the entrypoint
ENTRYPOINT ["/app/dingtalk-mcp"]
